

export const sampleReportData = [
    {
        "id": 1,
        "createdAt": "21-02-2024",
        "updatedAt": "23-02-2024",
        "createdBy": "Nguyễn Văn A",
        "updatedBy": "Nguyễn Văn B",
        "numberOfClocks": 12,
        "status": "1,3",
    },
    {
        "id": 12,
        "createdAt": "22-05-2024",
        "updatedAt": "25-05-2024",
        "createdBy": "Nguyễn Văn B",
        "updatedBy": "Nguyễn Văn C",
        "numberOfClocks": 24,
        "status": "1,2",
    },
    {
        "id": 32,
        "createdAt": "23-03-2024",
        "updatedAt": "26-03-2024",
        "createdBy": "Nguyễn Văn C",
        "updatedBy": "Nguyễn Văn D",
        "numberOfClocks": 36,
        "status": "1,2,3",
    },
    {
        "id": 43,
        "createdAt": "24-08-2024",
        "updatedAt": "27-08-2024",
        "createdBy": "Nguyễn Văn D",
        "updatedBy": "Nguyễn Văn E",
        "numberOfClocks": 48,
        "status": "3",
    },
    {
        "id": 54,
        "createdAt": "25-06-2024",
        "updatedAt": "28-06-2024",
        "createdBy": "Nguyễn Văn E",
        "updatedBy": "Nguyễn Văn F",
        "numberOfClocks": 60,
        "status": "1,3",
    },
    {
        "id": 12,
        "createdAt": "22-05-2024",
        "updatedAt": "25-05-2024",
        "createdBy": "Nguyễn Văn B",
        "updatedBy": "Nguyễn Văn C",
        "numberOfClocks": 24,
        "status": "1,2",
    },
    {
        "id": 32,
        "createdAt": "23-03-2024",
        "updatedAt": "26-03-2024",
        "createdBy": "Nguyễn Văn C",
        "updatedBy": "Nguyễn Văn D",
        "numberOfClocks": 36,
        "status": "1,2,3",
    },
    {
        "id": 43,
        "createdAt": "24-08-2024",
        "updatedAt": "27-08-2024",
        "createdBy": "Nguyễn Văn D",
        "updatedBy": "Nguyễn Văn E",
        "numberOfClocks": 48,
        "status": "3",
    },
    {
        "id": 54,
        "createdAt": "25-06-2024",
        "updatedAt": "28-06-2024",
        "createdBy": "Nguyễn Văn E",
        "updatedBy": "Nguyễn Văn F",
        "numberOfClocks": 60,
        "status": "1,3",
    }
]


export const sampleWaterMeterData = [
    {
        "id": 1,
        "serialNumber": "DH1234567890",
        "type":"Đa tia",
        "accuracyClass":"B",
        "createdAt": "21-02-2024",
        "updatedAt": "23-02-2024",
        "createdBy": "Nguyễn Văn A",
        "updatedBy": "Nguyễn Văn B",
        "status": "1",
    },
    {
        "id": 2,
        "serialNumber": "DH1234567891",
        "type":"Đơn tia",
        "accuracyClass":"A",
        "createdAt": "22-02-2024",
        "updatedAt": "24-02-2024",
        "createdBy": "Nguyễn Văn B",
        "updatedBy": "Nguyễn Văn C",
        "status": "0",
    },
    {
        "id": 3,
        "serialNumber": "DH1234567892",
        "type":"Woltman",
        "accuracyClass":"C",
        "createdAt": "23-02-2024",
        "updatedAt": "25-02-2024",
        "createdBy": "Nguyễn Văn C",
        "updatedBy": "Nguyễn Văn D",
        "status": "1",
    },
    {
        "id": 4,
        "serialNumber": "DH1234567893",
        "type":"Thể tích",
        "accuracyClass":"D",
        "createdAt": "24-02-2024",
        "updatedAt": "26-02-2024",
        "createdBy": "Nguyễn Văn D",
        "updatedBy": "Nguyễn Văn E",
        "status": "1",
    },
    {
        "id": 5,
        "serialNumber": "DH1234567894",
        "type":"Cơ - Điện từ",
        "accuracyClass":"B",
        "createdAt": "25-02-2024",
        "updatedAt": "27-02-2024",
        "createdBy": "Nguyễn Văn E",
        "updatedBy": "Nguyễn Văn F",
        "status": "1",
    },
    {
        "id": 6,
        "serialNumber": "DH1234567895",
        "type":"Điện từ",
        "accuracyClass":"A",
        "createdAt": "26-02-2024",
        "updatedAt": "28-02-2024",
        "createdBy": "Nguyễn Văn F",
        "updatedBy": "Nguyễn Văn G",
        "status": "1",
    },
    {
        "id": 7,
        "serialNumber": "DH1234567896",
        "type":"Đa tia",
        "accuracyClass":"1",
        "createdAt": "27-02-2024",
        "updatedAt": "01-03-2024",
        "createdBy": "Nguyễn Văn G",
        "updatedBy": "Nguyễn Văn H",
        "status": "0",
    },
    {
        "id": 8,
        "serialNumber": "DH1234567897",
        "type":"Đơn tia",
        "accuracyClass":"0.5",
        "createdAt": "28-02-2024",
        "updatedAt": "02-03-2024",
        "createdBy": "Nguyễn Văn H",
        "updatedBy": "Nguyễn Văn I",
        "status": "1",
    },
    {
        "id": 9,
        "serialNumber": "DH1234567898",
        "type":"Woltman",
        "accuracyClass":"B",
        "createdAt": "01-03-2024",
        "updatedAt": "03-03-2024",
        "createdBy": "Nguyễn Văn I",
        "updatedBy": "Nguyễn Văn J",
        "status": "1",
    },
    {
        "id": 10,
        "serialNumber": "DH1234567899",
        "type":"Thể tích",
        "accuracyClass":"A",
        "createdAt": "02-03-2024",
        "updatedAt": "04-03-2024",
        "createdBy": "Nguyễn Văn J",
        "updatedBy": "Nguyễn Văn K",
        "status": "1",
    },
    {
        "id": 11,
        "serialNumber": "DH1234567800",
        "type":"Cơ - Điện từ",
        "accuracyClass":"C",
        "createdAt": "03-03-2024",
        "updatedAt": "05-03-2024",
        "createdBy": "Nguyễn Văn K",
        "updatedBy": "Nguyễn Văn L",
        "status": "1",
    },
    {
        "id": 12,
        "serialNumber": "DH1234567801",
        "type":"Điện từ",
        "accuracyClass":"D",
        "createdAt": "04-03-2024",
        "updatedAt": "06-03-2024",
        "createdBy": "Nguyễn Văn L",
        "updatedBy": "Nguyễn Văn M",
        "status": "0",
    },
    {
        "id": 13,
        "serialNumber": "DH1234567802",
        "type":"Đa tia",
        "accuracyClass":"B",
        "createdAt": "05-03-2024",
        "updatedAt": "07-03-2024",
        "createdBy": "Nguyễn Văn M",
        "updatedBy": "Nguyễn Văn N",
        "status": "1",
    },
    {
        "id": 14,
        "serialNumber": "DH1234567803",
        "type":"Đơn tia",
        "accuracyClass":"A",
        "createdAt": "06-03-2024",
        "updatedAt": "08-03-2024",
        "createdBy": "Nguyễn Văn N",
        "updatedBy": "Nguyễn Văn O",
        "status": "1",
    },
    {
        "id": 15,
        "serialNumber": "DH1234567804",
        "type":"Woltman",
        "accuracyClass":"C",
        "createdAt": "07-03-2024",
        "updatedAt": "09-03-2024",
        "createdBy": "Nguyễn Văn O",
        "updatedBy": "Nguyễn Văn P",
        "status": "0",
    }
]

